#pragma config(Motor,  port2,           TR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           TL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BR,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int DEADZONE = 5;

void strafeLeft(int joyPos){
	motor[TL] = joyPos;
	motor[BL] = joyPos*-1;
	motor[TR] = joyPos*-1;
	motor[BR] = joyPos;
}

void strafeRight(int joyPos){
	motor[TL] = joyPos;
	motor[BL] = joyPos*-1;
	motor[TR] = joyPos*-1;
	motor[BR] = joyPos;
}

void moveForward(int joyPos){
	motor[TL] = joyPos;
	motor[BL] = joyPos;
	motor[TR] = joyPos;
	motor[BR] = joyPos;
}

void turn(int joyPos){
	motor[BL] = joyPos*-1;
	motor[TL] = joyPos*-1;
	motor[BR] = joyPos;
	motor[TR] = joyPos;
}


task main()
{
	while(true){
		if(vexRT[Ch4]>DEADZONE){
			strafeRight(vexRT[Ch4]);
		}
		else if(vexRT[Ch4]<0){
			strafeLeft(vexRT[Ch4]);
		}
		else if(vexRT[Ch2]!=0){
			moveForward(vexRT[Ch2]);
		}

		if(vexRT[Ch1]<0){
			turn(vexRT[Ch1]);
		}

	}

}
